name: test
on:
  push:
    branches:
      - "master"
      - "test/*"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: exit 0
        if: failure()
